[security]
session_secret = "PLEASE CHANGE THIS"
password_hash = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8" # "password"

[crawler]
crawl_delay = 1000

[application]
port = 5390
db_path = "./db.sqlite3"